POST http://localhost:9000/editpost
Content-Type: application/json

{
  "connectionkey": "FYR88m7kWtyHkjHa",
  "id": 2,
  "title": "john's new recruitment edited",
  "description": "looking for drivers",
  "address": "somewhere down south",
  "volunteerArea": "South",
  "jobType": "Transportation",
  "initialDate": "2024-08-14T00:00:00Z",
  "lastDate": "2024-09-29T23:59:59Z"
}
