POST http://localhost:9000/editpost
Content-Type: application/json

{
  "connectionkey": "WsyldYlt7lOpeRYV",
  "id": 1,
  "title": "john's new recruitment 8",
  "description": "looking for cooks",
  "address": "somewhere up north",
  "volunteerArea": "North",
  "jobType": "Cooking",
  "initialDate": "2024-08-14T00:00:00Z",
  "lastDate": "2024-08-16T23:59:59Z"
}
