POST http://localhost:9000/getfilteredposts
Content-Type: application/json

{
  "volunteerAreas": ["North"],
  "jobTypes": [],
  "initialDate": "2024-06-14T00:00:00Z",
  "endDate": "2024-10-14T00:00:00Z",
  "dateFilterType": "Contains",
  "connectionKey": "x75XJZvHQbyQoCGs"
}
